name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]  # Mantendo a versão mais recente do Python que você mencionou

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # Atualizado para a versão mais recente do setup-python

    - name: Install poetry
      run: |
        python -m ensurepip --upgrade  # Garante que o ensurepip está atualizado
        python -m pip install --upgrade pip  # Atualiza o pip para a versão mais recente
        python -m pip install --upgrade poetry  # Atualiza o poetry para a versão mais recente

    - name: View poetry --help
      run: poetry --help

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: Test
      run: |
        poetry run python manage.py test
